version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"